In [93]:
# all imports

import json
import csv
import pandas as pd
import sklearn.feature_extraction.text as sk_text
import nltk
#nltk.download()
from nltk.corpus import stopwords

In [2]:
# create tsv file with selected attibutes of reviews.json

outfile = open("review_stars.tsv", 'w')
sfile = csv.writer(outfile, delimiter ="\t", quoting=csv.QUOTE_MINIMAL)
sfile.writerow(['business_id','stars', 'text'])
with open('yelp_dataset/yelp_academic_dataset_review.json') as f:
    for line in f:
        row = json.loads(line)
        # some special char must be encoded in 'utf-8'
        sfile.writerow([row['business_id'], row['stars'], row['text']])

outfile.close()

review_df= pd.read_csv('review_stars.tsv', delimiter ="\t")

In [9]:
review_df= pd.read_csv('review_stars.tsv', delimiter ="\t", nrows=10000)

In [3]:
# create tsv file with selected attibutes of business.json

outfile = open("business.tsv", 'w')
sfile = csv.writer(outfile, delimiter ="\t", quoting=csv.QUOTE_MINIMAL)
sfile.writerow(['business_id','categories', 'stars', 'review_count'])
with open('yelp_dataset/yelp_academic_dataset_business.json') as f:
    for line in f:
        row = json.loads(line)
        # some special char must be encoded in 'utf-8'
        sfile.writerow([row['business_id'], row['categories'], row['stars'],row['review_count'] ])

outfile.close()

business_df= pd.read_csv('business.tsv', delimiter ="\t")

In [7]:
review_df.dtypes


business_id    object
stars           int64
text           object
dtype: object

In [11]:
# group-by business id

review_agg_df = review_df.groupby('business_id')['text'].sum()

In [57]:
# join both files and create new

merge_df = pd.merge(business_df, df_ready_for_sklearn, on='business_id')

In [58]:
# for Sk learn

df_ready_for_sklearn = pd.DataFrame({'business_id': review_agg_df.index, 'all_reviews': review_agg_df.values})

In [59]:
merge_df

business_id  \
0     DR30lzIHVTF6xhyMI-3IlQ   
1     YIez_A3WOt9J2SXN7OMa2Q   
2     Gc8R7b3I3CTwAiWv7MjtSg   
3     pIzuXtFdkj8fHuzJfYiwqw   
4     5T6kFKFycym_GkhgOiysIw   
5     OyJDaAAMr220qkZsovCARQ   
6     YkAIlxYZ1guSqbbowU9X4g   
7     ZQ-7uFQk21NHoOzJfhEjBw   
8     2ktKjN5z8EcqmUv6EDiDgA   
9     ohYgabP6PqkNsF0vnZUxeg   
10    sYKB4nITCLLFcCZPn3QECQ   
11    ADmJgVJ82zdLzffdaH1gVw   
12    V90fC_aF-_DNYzQvUtbLww   
13    TmGxQgFdiG585PCs_2hCew   
14    QoXT0qI6_3WeHImUuLAyjg   
15    lHazo7qKEcSc62PMUW3oaw   
16    wcNvlrB5xSxzXex2M3UyvQ   
17    D31JSfofD0dYbIx7Yak2Yw   
18    YGaowC1J4GfkQYyYLYWnQQ   
19    glkEaoxbewiSMBiXs945JA   
20    42-UJ-c_97IeqUc6BWjmnA   
21    nUaLFTfUqVKMFQonsWBnag   
22    Jy96qxfFFH4Wa-KhkmwSMw   
23    lYFpDTiVMNrpkpFyIEcc_w   
24    hsRjct8UiUHU54B983GmcA   
25    60N91qkHqdFCsyUMd_qVLA   
26    I-3pI0DeW3VYJ6mpUyDNSw   
27    zrDi4gEaUi64lAMfJU51dw   
28    ha_mea2KXpVgHwxD0RDLGQ   
29    yEOu75XjwczngvWWlr0M_A   
...                      ...   
8547  9yESUcIVarhYEabIMj844Q   
8548  Nmfvhyxi7gruNGs_hfWc3w   
8549  eMLvsFmMFtzTaIn1LJJbdQ   
8550  PWW_jT4tHP_r1S18ePJyTQ   
8551  wFNxIIn4_G2hf6R8PJPU5w   
8552  OgqZepyL6UesV6oHtdvI1A   
8553  6xgcHeLad-VaoTIQewK84A   
8554  904-MfAZ28poGitmdqoBMA   
8555  X67a8NpGhqQWdzZt0zuCQg   
8556  Gj7QZ0kV-32MAVhJQsWlmg   
8557  -UV2tt3gy57-5a29paA_4w   
8558  5k34OJo3BsEaoyMsW86eZg   
8559  pgSc8dBFiyAc0Cxzx1ryuw   
8560  cYwJA2A6I12KNkm2rtXd5g   
8561  lu-94OWHJBV0MZET7KVNpA   
8562  4LXZzgsrM1ZyS_-uB9Od2Q   
8563  oeRLD870Z76FD1OYW8jbSQ   
8564  OCEAe7tjPbDmcWWvRFUwwQ   
8565  Fcy6hCkemQoDXCs5ayvcxg   
8566  T1HBJyu_wNcpvsGlMHlODg   
8567  PdDpIGwBZoTYzOVasT-WuA   
8568  PDIh1lVtKlUqPJROXYJQvQ   
8569  WpI5MZC3XzlTpcUOKXzCbA   
8570  8A8-xCeCZ3mKcpYT_P8_qQ   
8571  g62SlImzhs6_1t-knPjd8w   
8572  rnNFE7-zE5BFKjFURBEpJw   
8573  _eysP-l3yXpCqMHOQEptdQ   
8574  p2qoi-QKUs_p6QkDEKVNOg   
8575  W5d8iNog90R-qw43m5dGwg   
8576  1UmZSifNBsygSWzbfKiAew   

                                             categories  stars  review_count  \
0     Thrift Stores, Shopping, Used, Vintage & Consi...    3.5            17   
1                Caribbean, Food, Bakeries, Restaurants    4.0           105   
2                   Body Shops, Auto Repair, Automotive    4.5            24   
3     Restaurants, Event Planning & Services, Italia...    4.5             3   
4                      Poutineries, Restaurants, Diners    4.0          1565   
5                                    Food, Coffee & Tea    3.0            49   
6     Restaurants, Chinese, Dim Sum, Breakfast & Brunch    3.5           171   
7                                    Coffee & Tea, Food    3.0            59   
8     Fashion, Department Stores, Automotive, Shoppi...    3.5           121   
9     Arts & Entertainment, Coffee & Tea, Bars, Food...    4.5           149   
10                          Japanese, Restaurants, Food    3.5            58   
11    Food, Specialty Food, Organic Stores, Health M...    3.5            14   
12    Hotels & Travel, Asian Fusion, Day Spas, Casin...    3.5           246   
13    Desserts, Food, Shaved Ice, Ice Cream & Frozen...    4.5            35   
14              Restaurants, Breakfast & Brunch, Diners    3.5           110   
15    Tapas Bars, Food, Canadian (New), Restaurants,...    4.0            62   
16    Nightlife, Sports Bars, Bars, Restaurants, Kar...    3.0           116   
17    Restaurants, Food, American (Traditional), Cof...    3.0            76   
18                                 Restaurants, Mexican    3.5            19   
19                             Pizza, Food, Restaurants    3.5           466   
20                        Restaurants, Thai, Vietnamese    2.5            66   
21    Restaurants, Food, Bakeries, Grocery, Delis, B...    4.0           147   
22                      Food, Ice Cream & Frozen Yogurt    4.0            68   
23                  Shopping, Vape Shops, Tobacco Shops    5.0            76   
24    Meat Shops, Seafood, Groce

In [60]:
from scipy.stats import zscore
merge_df['review_count'] = zscore(merge_df['review_count'])

In [61]:
merge_df

business_id  \
0     DR30lzIHVTF6xhyMI-3IlQ   
1     YIez_A3WOt9J2SXN7OMa2Q   
2     Gc8R7b3I3CTwAiWv7MjtSg   
3     pIzuXtFdkj8fHuzJfYiwqw   
4     5T6kFKFycym_GkhgOiysIw   
5     OyJDaAAMr220qkZsovCARQ   
6     YkAIlxYZ1guSqbbowU9X4g   
7     ZQ-7uFQk21NHoOzJfhEjBw   
8     2ktKjN5z8EcqmUv6EDiDgA   
9     ohYgabP6PqkNsF0vnZUxeg   
10    sYKB4nITCLLFcCZPn3QECQ   
11    ADmJgVJ82zdLzffdaH1gVw   
12    V90fC_aF-_DNYzQvUtbLww   
13    TmGxQgFdiG585PCs_2hCew   
14    QoXT0qI6_3WeHImUuLAyjg   
15    lHazo7qKEcSc62PMUW3oaw   
16    wcNvlrB5xSxzXex2M3UyvQ   
17    D31JSfofD0dYbIx7Yak2Yw   
18    YGaowC1J4GfkQYyYLYWnQQ   
19    glkEaoxbewiSMBiXs945JA   
20    42-UJ-c_97IeqUc6BWjmnA   
21    nUaLFTfUqVKMFQonsWBnag   
22    Jy96qxfFFH4Wa-KhkmwSMw   
23    lYFpDTiVMNrpkpFyIEcc_w   
24    hsRjct8UiUHU54B983GmcA   
25    60N91qkHqdFCsyUMd_qVLA   
26    I-3pI0DeW3VYJ6mpUyDNSw   
27    zrDi4gEaUi64lAMfJU51dw   
28    ha_mea2KXpVgHwxD0RDLGQ   
29    yEOu75XjwczngvWWlr0M_A   
...                      ...   
8547  9yESUcIVarhYEabIMj844Q   
8548  Nmfvhyxi7gruNGs_hfWc3w   
8549  eMLvsFmMFtzTaIn1LJJbdQ   
8550  PWW_jT4tHP_r1S18ePJyTQ   
8551  wFNxIIn4_G2hf6R8PJPU5w   
8552  OgqZepyL6UesV6oHtdvI1A   
8553  6xgcHeLad-VaoTIQewK84A   
8554  904-MfAZ28poGitmdqoBMA   
8555  X67a8NpGhqQWdzZt0zuCQg   
8556  Gj7QZ0kV-32MAVhJQsWlmg   
8557  -UV2tt3gy57-5a29paA_4w   
8558  5k34OJo3BsEaoyMsW86eZg   
8559  pgSc8dBFiyAc0Cxzx1ryuw   
8560  cYwJA2A6I12KNkm2rtXd5g   
8561  lu-94OWHJBV0MZET7KVNpA   
8562  4LXZzgsrM1ZyS_-uB9Od2Q   
8563  oeRLD870Z76FD1OYW8jbSQ   
8564  OCEAe7tjPbDmcWWvRFUwwQ   
8565  Fcy6hCkemQoDXCs5ayvcxg   
8566  T1HBJyu_wNcpvsGlMHlODg   
8567  PdDpIGwBZoTYzOVasT-WuA   
8568  PDIh1lVtKlUqPJROXYJQvQ   
8569  WpI5MZC3XzlTpcUOKXzCbA   
8570  8A8-xCeCZ3mKcpYT_P8_qQ   
8571  g62SlImzhs6_1t-knPjd8w   
8572  rnNFE7-zE5BFKjFURBEpJw   
8573  _eysP-l3yXpCqMHOQEptdQ   
8574  p2qoi-QKUs_p6QkDEKVNOg   
8575  W5d8iNog90R-qw43m5dGwg   
8576  1UmZSifNBsygSWzbfKiAew   

                                             categories  stars  review_count  \
0     Thrift Stores, Shopping, Used, Vintage & Consi...    3.5     -0.445046   
1                Caribbean, Food, Bakeries, Restaurants    4.0     -0.214820   
2                   Body Shops, Auto Repair, Automotive    4.5     -0.426732   
3     Restaurants, Event Planning & Services, Italia...    4.5     -0.481673   
4                      Poutineries, Restaurants, Diners    4.0      3.604839   
5                                    Food, Coffee & Tea    3.0     -0.361327   
6     Restaurants, Chinese, Dim Sum, Breakfast & Brunch    3.5     -0.042150   
7                                    Coffee & Tea, Food    3.0     -0.335165   
8     Fashion, Department Stores, Automotive, Shoppi...    3.5     -0.172960   
9     Arts & Entertainment, Coffee & Tea, Bars, Food...    4.5     -0.099707   
10                          Japanese, Restaurants, Food    3.5     -0.337781   
11    Food, Specialty Food, Organic Stores, Health M...    3.5     -0.452894   
12    Hotels & Travel, Asian Fusion, Day Spas, Casin...    3.5      0.154065   
13    Desserts, Food, Shaved Ice, Ice Cream & Frozen...    4.5     -0.397954   
14              Restaurants, Breakfast & Brunch, Diners    3.5     -0.201739   
15    Tapas Bars, Food, Canadian (New), Restaurants,...    4.0     -0.327317   
16    Nightlife, Sports Bars, Bars, Restaurants, Kar...    3.0     -0.186042   
17    Restaurants, Food, American (Traditional), Cof...    3.0     -0.290690   
18                                 Restaurants, Mexican    3.5     -0.439813   
19                             Pizza, Food, Restaurants    3.5      0.729630   
20                        Restaurants, Thai, Vietnamese    2.5     -0.316852   
21    Restaurants, Food, Bakeries, Grocery, Delis, B...    4.0     -0.104939   
22                      Food, Ice Cream & Frozen Yogurt    4.0     -0.311619   
23                  Shopping, Vape Shops, Tobacco Shops    5.0     -0.290690   
24    Meat Shops, Seafood, Groce

In [62]:
merge_df['all_reviews'] = merge_df['all_reviews'].str.lower()

In [63]:
merge_df['categories'] = merge_df['categories'].str.lower()

In [64]:
merge_df['all_reviews'] = merge_df['all_reviews'].str.strip()
merge_df['categories'] = merge_df['categories'].str.strip()

In [65]:
merge_df['all_reviews'] = merge_df['all_reviews'].str.split()
merge_df['categories'] = merge_df['categories'].str.split()

In [66]:
merge_df

business_id  \
0     DR30lzIHVTF6xhyMI-3IlQ   
1     YIez_A3WOt9J2SXN7OMa2Q   
2     Gc8R7b3I3CTwAiWv7MjtSg   
3     pIzuXtFdkj8fHuzJfYiwqw   
4     5T6kFKFycym_GkhgOiysIw   
5     OyJDaAAMr220qkZsovCARQ   
6     YkAIlxYZ1guSqbbowU9X4g   
7     ZQ-7uFQk21NHoOzJfhEjBw   
8     2ktKjN5z8EcqmUv6EDiDgA   
9     ohYgabP6PqkNsF0vnZUxeg   
10    sYKB4nITCLLFcCZPn3QECQ   
11    ADmJgVJ82zdLzffdaH1gVw   
12    V90fC_aF-_DNYzQvUtbLww   
13    TmGxQgFdiG585PCs_2hCew   
14    QoXT0qI6_3WeHImUuLAyjg   
15    lHazo7qKEcSc62PMUW3oaw   
16    wcNvlrB5xSxzXex2M3UyvQ   
17    D31JSfofD0dYbIx7Yak2Yw   
18    YGaowC1J4GfkQYyYLYWnQQ   
19    glkEaoxbewiSMBiXs945JA   
20    42-UJ-c_97IeqUc6BWjmnA   
21    nUaLFTfUqVKMFQonsWBnag   
22    Jy96qxfFFH4Wa-KhkmwSMw   
23    lYFpDTiVMNrpkpFyIEcc_w   
24    hsRjct8UiUHU54B983GmcA   
25    60N91qkHqdFCsyUMd_qVLA   
26    I-3pI0DeW3VYJ6mpUyDNSw   
27    zrDi4gEaUi64lAMfJU51dw   
28    ha_mea2KXpVgHwxD0RDLGQ   
29    yEOu75XjwczngvWWlr0M_A   
...                      ...   
8547  9yESUcIVarhYEabIMj844Q   
8548  Nmfvhyxi7gruNGs_hfWc3w   
8549  eMLvsFmMFtzTaIn1LJJbdQ   
8550  PWW_jT4tHP_r1S18ePJyTQ   
8551  wFNxIIn4_G2hf6R8PJPU5w   
8552  OgqZepyL6UesV6oHtdvI1A   
8553  6xgcHeLad-VaoTIQewK84A   
8554  904-MfAZ28poGitmdqoBMA   
8555  X67a8NpGhqQWdzZt0zuCQg   
8556  Gj7QZ0kV-32MAVhJQsWlmg   
8557  -UV2tt3gy57-5a29paA_4w   
8558  5k34OJo3BsEaoyMsW86eZg   
8559  pgSc8dBFiyAc0Cxzx1ryuw   
8560  cYwJA2A6I12KNkm2rtXd5g   
8561  lu-94OWHJBV0MZET7KVNpA   
8562  4LXZzgsrM1ZyS_-uB9Od2Q   
8563  oeRLD870Z76FD1OYW8jbSQ   
8564  OCEAe7tjPbDmcWWvRFUwwQ   
8565  Fcy6hCkemQoDXCs5ayvcxg   
8566  T1HBJyu_wNcpvsGlMHlODg   
8567  PdDpIGwBZoTYzOVasT-WuA   
8568  PDIh1lVtKlUqPJROXYJQvQ   
8569  WpI5MZC3XzlTpcUOKXzCbA   
8570  8A8-xCeCZ3mKcpYT_P8_qQ   
8571  g62SlImzhs6_1t-knPjd8w   
8572  rnNFE7-zE5BFKjFURBEpJw   
8573  _eysP-l3yXpCqMHOQEptdQ   
8574  p2qoi-QKUs_p6QkDEKVNOg   
8575  W5d8iNog90R-qw43m5dGwg   
8576  1UmZSifNBsygSWzbfKiAew   

                                             categories  stars  review_count  \
0     [thrift, stores,, shopping,, used,, vintage, &...    3.5     -0.445046   
1           [caribbean,, food,, bakeries,, restaurants]    4.0     -0.214820   
2             [body, shops,, auto, repair,, automotive]    4.5     -0.426732   
3     [restaurants,, event, planning, &, services,, ...    4.5     -0.481673   
4                  [poutineries,, restaurants,, diners]    4.0      3.604839   
5                               [food,, coffee, &, tea]    3.0     -0.361327   
6     [restaurants,, chinese,, dim, sum,, breakfast,...    3.5     -0.042150   
7                               [coffee, &, tea,, food]    3.0     -0.335165   
8     [fashion,, department, stores,, automotive,, s...    3.5     -0.172960   
9     [arts, &, entertainment,, coffee, &, tea,, bar...    4.5     -0.099707   
10                      [japanese,, restaurants,, food]    3.5     -0.337781   
11    [food,, specialty, food,, organic, stores,, he...    3.5     -0.452894   
12    [hotels, &, travel,, asian, fusion,, day, spas...    3.5      0.154065   
13    [desserts,, food,, shaved, ice,, ice, cream, &...    4.5     -0.397954   
14        [restaurants,, breakfast, &, brunch,, diners]    3.5     -0.201739   
15    [tapas, bars,, food,, canadian, (new),, restau...    4.0     -0.327317   
16    [nightlife,, sports, bars,, bars,, restaurants...    3.0     -0.186042   
17    [restaurants,, food,, american, (traditional),...    3.0     -0.290690   
18                              [restaurants,, mexican]    3.5     -0.439813   
19                         [pizza,, food,, restaurants]    3.5      0.729630   
20                    [restaurants,, thai,, vietnamese]    2.5     -0.316852   
21    [restaurants,, food,, bakeries,, grocery,, del...    4.0     -0.104939   
22               [food,, ice, cream, &, frozen, yogurt]    4.0     -0.311619   
23            [shopping,, vape, shops,, tobacco, shops]    5.0     -0.290690   
24    [meat, shops,, seafood,, g

In [77]:
stop = stopwords.words("english")
merge_df['all_reviews'] = merge_df['all_reviews'].apply(lambda x: ' '.join([word for word in x if word not in (stop)]))

In [78]:
merge_df

business_id  \
0     DR30lzIHVTF6xhyMI-3IlQ   
1     YIez_A3WOt9J2SXN7OMa2Q   
2     Gc8R7b3I3CTwAiWv7MjtSg   
3     pIzuXtFdkj8fHuzJfYiwqw   
4     5T6kFKFycym_GkhgOiysIw   
5     OyJDaAAMr220qkZsovCARQ   
6     YkAIlxYZ1guSqbbowU9X4g   
7     ZQ-7uFQk21NHoOzJfhEjBw   
8     2ktKjN5z8EcqmUv6EDiDgA   
9     ohYgabP6PqkNsF0vnZUxeg   
10    sYKB4nITCLLFcCZPn3QECQ   
11    ADmJgVJ82zdLzffdaH1gVw   
12    V90fC_aF-_DNYzQvUtbLww   
13    TmGxQgFdiG585PCs_2hCew   
14    QoXT0qI6_3WeHImUuLAyjg   
15    lHazo7qKEcSc62PMUW3oaw   
16    wcNvlrB5xSxzXex2M3UyvQ   
17    D31JSfofD0dYbIx7Yak2Yw   
18    YGaowC1J4GfkQYyYLYWnQQ   
19    glkEaoxbewiSMBiXs945JA   
20    42-UJ-c_97IeqUc6BWjmnA   
21    nUaLFTfUqVKMFQonsWBnag   
22    Jy96qxfFFH4Wa-KhkmwSMw   
23    lYFpDTiVMNrpkpFyIEcc_w   
24    hsRjct8UiUHU54B983GmcA   
25    60N91qkHqdFCsyUMd_qVLA   
26    I-3pI0DeW3VYJ6mpUyDNSw   
27    zrDi4gEaUi64lAMfJU51dw   
28    ha_mea2KXpVgHwxD0RDLGQ   
29    yEOu75XjwczngvWWlr0M_A   
...                      ...   
8547  9yESUcIVarhYEabIMj844Q   
8548  Nmfvhyxi7gruNGs_hfWc3w   
8549  eMLvsFmMFtzTaIn1LJJbdQ   
8550  PWW_jT4tHP_r1S18ePJyTQ   
8551  wFNxIIn4_G2hf6R8PJPU5w   
8552  OgqZepyL6UesV6oHtdvI1A   
8553  6xgcHeLad-VaoTIQewK84A   
8554  904-MfAZ28poGitmdqoBMA   
8555  X67a8NpGhqQWdzZt0zuCQg   
8556  Gj7QZ0kV-32MAVhJQsWlmg   
8557  -UV2tt3gy57-5a29paA_4w   
8558  5k34OJo3BsEaoyMsW86eZg   
8559  pgSc8dBFiyAc0Cxzx1ryuw   
8560  cYwJA2A6I12KNkm2rtXd5g   
8561  lu-94OWHJBV0MZET7KVNpA   
8562  4LXZzgsrM1ZyS_-uB9Od2Q   
8563  oeRLD870Z76FD1OYW8jbSQ   
8564  OCEAe7tjPbDmcWWvRFUwwQ   
8565  Fcy6hCkemQoDXCs5ayvcxg   
8566  T1HBJyu_wNcpvsGlMHlODg   
8567  PdDpIGwBZoTYzOVasT-WuA   
8568  PDIh1lVtKlUqPJROXYJQvQ   
8569  WpI5MZC3XzlTpcUOKXzCbA   
8570  8A8-xCeCZ3mKcpYT_P8_qQ   
8571  g62SlImzhs6_1t-knPjd8w   
8572  rnNFE7-zE5BFKjFURBEpJw   
8573  _eysP-l3yXpCqMHOQEptdQ   
8574  p2qoi-QKUs_p6QkDEKVNOg   
8575  W5d8iNog90R-qw43m5dGwg   
8576  1UmZSifNBsygSWzbfKiAew   

                                             categories  stars  review_count  \
0     [thrift, stores,, shopping,, used,, vintage, &...    3.5     -0.445046   
1           [caribbean,, food,, bakeries,, restaurants]    4.0     -0.214820   
2             [body, shops,, auto, repair,, automotive]    4.5     -0.426732   
3     [restaurants,, event, planning, &, services,, ...    4.5     -0.481673   
4                  [poutineries,, restaurants,, diners]    4.0      3.604839   
5                               [food,, coffee, &, tea]    3.0     -0.361327   
6     [restaurants,, chinese,, dim, sum,, breakfast,...    3.5     -0.042150   
7                               [coffee, &, tea,, food]    3.0     -0.335165   
8     [fashion,, department, stores,, automotive,, s...    3.5     -0.172960   
9     [arts, &, entertainment,, coffee, &, tea,, bar...    4.5     -0.099707   
10                      [japanese,, restaurants,, food]    3.5     -0.337781   
11    [food,, specialty, food,, organic, stores,, he...    3.5     -0.452894   
12    [hotels, &, travel,, asian, fusion,, day, spas...    3.5      0.154065   
13    [desserts,, food,, shaved, ice,, ice, cream, &...    4.5     -0.397954   
14        [restaurants,, breakfast, &, brunch,, diners]    3.5     -0.201739   
15    [tapas, bars,, food,, canadian, (new),, restau...    4.0     -0.327317   
16    [nightlife,, sports, bars,, bars,, restaurants...    3.0     -0.186042   
17    [restaurants,, food,, american, (traditional),...    3.0     -0.290690   
18                              [restaurants,, mexican]    3.5     -0.439813   
19                         [pizza,, food,, restaurants]    3.5      0.729630   
20                    [restaurants,, thai,, vietnamese]    2.5     -0.316852   
21    [restaurants,, food,, bakeries,, grocery,, del...    4.0     -0.104939   
22               [food,, ice, cream, &, frozen, yogurt]    4.0     -0.311619   
23            [shopping,, vape, shops,, tobacco, shops]    5.0     -0.290690   
24    [meat, shops,, seafood,, g

In [83]:
merge_df['all_reviews'] = merge_df['all_reviews'].str.strip()
merge_df['all_reviews'] = merge_df['all_reviews'].str.split()

In [84]:
merge_df

business_id  \
0     DR30lzIHVTF6xhyMI-3IlQ   
1     YIez_A3WOt9J2SXN7OMa2Q   
2     Gc8R7b3I3CTwAiWv7MjtSg   
3     pIzuXtFdkj8fHuzJfYiwqw   
4     5T6kFKFycym_GkhgOiysIw   
5     OyJDaAAMr220qkZsovCARQ   
6     YkAIlxYZ1guSqbbowU9X4g   
7     ZQ-7uFQk21NHoOzJfhEjBw   
8     2ktKjN5z8EcqmUv6EDiDgA   
9     ohYgabP6PqkNsF0vnZUxeg   
10    sYKB4nITCLLFcCZPn3QECQ   
11    ADmJgVJ82zdLzffdaH1gVw   
12    V90fC_aF-_DNYzQvUtbLww   
13    TmGxQgFdiG585PCs_2hCew   
14    QoXT0qI6_3WeHImUuLAyjg   
15    lHazo7qKEcSc62PMUW3oaw   
16    wcNvlrB5xSxzXex2M3UyvQ   
17    D31JSfofD0dYbIx7Yak2Yw   
18    YGaowC1J4GfkQYyYLYWnQQ   
19    glkEaoxbewiSMBiXs945JA   
20    42-UJ-c_97IeqUc6BWjmnA   
21    nUaLFTfUqVKMFQonsWBnag   
22    Jy96qxfFFH4Wa-KhkmwSMw   
23    lYFpDTiVMNrpkpFyIEcc_w   
24    hsRjct8UiUHU54B983GmcA   
25    60N91qkHqdFCsyUMd_qVLA   
26    I-3pI0DeW3VYJ6mpUyDNSw   
27    zrDi4gEaUi64lAMfJU51dw   
28    ha_mea2KXpVgHwxD0RDLGQ   
29    yEOu75XjwczngvWWlr0M_A   
...                      ...   
8547  9yESUcIVarhYEabIMj844Q   
8548  Nmfvhyxi7gruNGs_hfWc3w   
8549  eMLvsFmMFtzTaIn1LJJbdQ   
8550  PWW_jT4tHP_r1S18ePJyTQ   
8551  wFNxIIn4_G2hf6R8PJPU5w   
8552  OgqZepyL6UesV6oHtdvI1A   
8553  6xgcHeLad-VaoTIQewK84A   
8554  904-MfAZ28poGitmdqoBMA   
8555  X67a8NpGhqQWdzZt0zuCQg   
8556  Gj7QZ0kV-32MAVhJQsWlmg   
8557  -UV2tt3gy57-5a29paA_4w   
8558  5k34OJo3BsEaoyMsW86eZg   
8559  pgSc8dBFiyAc0Cxzx1ryuw   
8560  cYwJA2A6I12KNkm2rtXd5g   
8561  lu-94OWHJBV0MZET7KVNpA   
8562  4LXZzgsrM1ZyS_-uB9Od2Q   
8563  oeRLD870Z76FD1OYW8jbSQ   
8564  OCEAe7tjPbDmcWWvRFUwwQ   
8565  Fcy6hCkemQoDXCs5ayvcxg   
8566  T1HBJyu_wNcpvsGlMHlODg   
8567  PdDpIGwBZoTYzOVasT-WuA   
8568  PDIh1lVtKlUqPJROXYJQvQ   
8569  WpI5MZC3XzlTpcUOKXzCbA   
8570  8A8-xCeCZ3mKcpYT_P8_qQ   
8571  g62SlImzhs6_1t-knPjd8w   
8572  rnNFE7-zE5BFKjFURBEpJw   
8573  _eysP-l3yXpCqMHOQEptdQ   
8574  p2qoi-QKUs_p6QkDEKVNOg   
8575  W5d8iNog90R-qw43m5dGwg   
8576  1UmZSifNBsygSWzbfKiAew   

                                             categories  stars  review_count  \
0     [thrift, stores,, shopping,, used,, vintage, &...    3.5     -0.445046   
1           [caribbean,, food,, bakeries,, restaurants]    4.0     -0.214820   
2             [body, shops,, auto, repair,, automotive]    4.5     -0.426732   
3     [restaurants,, event, planning, &, services,, ...    4.5     -0.481673   
4                  [poutineries,, restaurants,, diners]    4.0      3.604839   
5                               [food,, coffee, &, tea]    3.0     -0.361327   
6     [restaurants,, chinese,, dim, sum,, breakfast,...    3.5     -0.042150   
7                               [coffee, &, tea,, food]    3.0     -0.335165   
8     [fashion,, department, stores,, automotive,, s...    3.5     -0.172960   
9     [arts, &, entertainment,, coffee, &, tea,, bar...    4.5     -0.099707   
10                      [japanese,, restaurants,, food]    3.5     -0.337781   
11    [food,, specialty, food,, organic, stores,, he...    3.5     -0.452894   
12    [hotels, &, travel,, asian, fusion,, day, spas...    3.5      0.154065   
13    [desserts,, food,, shaved, ice,, ice, cream, &...    4.5     -0.397954   
14        [restaurants,, breakfast, &, brunch,, diners]    3.5     -0.201739   
15    [tapas, bars,, food,, canadian, (new),, restau...    4.0     -0.327317   
16    [nightlife,, sports, bars,, bars,, restaurants...    3.0     -0.186042   
17    [restaurants,, food,, american, (traditional),...    3.0     -0.290690   
18                              [restaurants,, mexican]    3.5     -0.439813   
19                         [pizza,, food,, restaurants]    3.5      0.729630   
20                    [restaurants,, thai,, vietnamese]    2.5     -0.316852   
21    [restaurants,, food,, bakeries,, grocery,, del...    4.0     -0.104939   
22               [food,, ice, cream, &, frozen, yogurt]    4.0     -0.311619   
23            [shopping,, vape, shops,, tobacco, shops]    5.0     -0.290690   
24    [meat, shops,, seafood,, g

In [92]:
vectorizer = sk_text.TfidfVectorizer(lowercase=False,
                                 #stop_words='english',
                                 #max_features = 1000,
                                 min_df=1)
matrix = vectorizer.fit_transform(merge_df['all_reviews'])

TypeError: expected string or bytes-like object

In [82]:
print(type(matrix))          # Compressed Sparse Row matrix
print(matrix.toarray())        #  convert it to numpy array

print(vectorizer.get_feature_names())

<class 'scipy.sparse.csr.csr_matrix'>
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['00', '000', '00am', '00p', '00pm', '01', '010', '02', '02pm', '03', '0308', '04', '05', '06', '06pm', '07', '0700', '072', '0723', '08', '087', '09', '0952', '0lace', '10', '100', '1000', '100000000', '1000s', '100f', '100x', '101', '102', '103', '1030', '104', '1040', '1043', '105', '1055', '107', '109', '10am', '10days', '10h20', '10h30pm', '10hrs', '10ish', '10k', '10m', '10mbps', '10mile', '10min', '10mins', '10oz', '10pm', '10th', '10w', '10x', '10yrs', '11', '110', '1100', '1105', '111', '112', '113', '1130a', '1146', '115', '116', '117', '118', '1180', '118a', '119', '1198', '11am', '11pm', '11th', '12', '120', '1200', '122', '1230', '125', '1250', '128', '129', '12am', '12mg', '12mil', '12oz', '12pm', '12th', '12x12', '13', '130', '130am', '134', '135', '13th', '13ys', '14', '140', '14